name: Flutter Build & Sonar Analysis

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
N
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'

      - name: Install dependencies
        run: flutter pub get
        working-directory: AppReceitas

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 
        with:
          projectBaseDir: AppReceitas

      - name: Install System Dependencies (Graphviz & PlantUML)
        run: sudo apt-get update && sudo apt-get install -y graphviz plantuml

      - name: Install dcdg (Dart Class Diagram Generator)
        run: dart pub global activate dcdg

      - name: Generate UML Class Diagram
        working-directory: AppReceitas
        run: |
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          dcdg -o domain_classes.puml
          plantuml domain_classes.puml

      - name: Upload UML Diagram Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uml-class-diagram
          path: AppReceitas/domain_classes.png
          retention-days: 5

      - name: Check code style (dart format)
        working-directory: AppReceitas
        run: dart format . --set-exit-if-changed --output=none

      - name: Detect Code Duplication (jscpd)
        run: |
          npm install -g jscpd
          jscpd AppReceitas/lib --min-lines 5 --threshold 0 --ignore "**/*.g.dart" --reporters "console"

      - name: Analyze code (fail only on deprecated)
        working-directory: AppReceitas
        run: |
          flutter analyze > analyze_log.txt || true
          if grep -q "deprecated_member_use" analyze_log.txt; then
            echo "‚ùå Found deprecated code usage!"
            grep "deprecated_member_use" analyze_log.txt
            exit 1
          fi

      - name: Build APK (debug)
        run: flutter build apk --debug
        working-directory: AppReceitas
