name: Flutter Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'

      - name: Install dependencies
        run: flutter pub get
        working-directory: AppReceitas

      - name: Check code style (dart format)
        working-directory: AppReceitas
        run: |
          echo "üîç Checking code formatting..."
          dart format . --set-exit-if-changed --output=none

      - name: Detect Code Duplication
        run: |
          echo "Installing jscpd..."
          npm install -g jscpd
          echo "üîç Checking for duplicated code..."
          # Verifica a pasta lib dentro de AppReceitas
          # threshold 0 = Falha com qualquer duplica√ß√£o
          # ignore = Ignora arquivos gerados pelo Flutter (.g.dart)
          jscpd AppReceitas/lib --min-lines 5 --threshold 0 --ignore "**/*.g.dart" --reporters "console"

      - name: Analyze code (fail only on deprecated)
        working-directory: AppReceitas
        run: |
          echo "Running Flutter Analyze..."
          flutter analyze > analyze_log.txt || true

          echo "Checking for deprecated usages..."
          if grep -q "deprecated_member_use" analyze_log.txt; then
            echo "‚ùå Found deprecated code usage!"
            grep "deprecated_member_use" analyze_log.txt
            exit 1
          else
            echo "‚úÖ No deprecated code found."
          fi

      - name: Build APK (debug)
        run: flutter build apk --debug
        working-directory: AppReceitas